### PR TITLE
feat(test-module): support tflint --fix

### LINKED ISSUE #2175: Question: Is the absence of a fix flag in the inputs of "github-action-tflint" when called from the "test-module" intentional by design?
### Question

The "github-action-tflint" called in "[test-module](https://github.com/suzuki-shunsuke/tfaction/blob/main/test-module/action.yaml)" does not have a fix flag in its inputs, whereas the one called in "[test](https://github.com/suzuki-shunsuke/tfaction/blob/main/test/action.yaml)" does include a fix flag.

### Call github-action-tflint in test-module
image

### Call github-action-tflint in test
image

### Background

_No response_

### Note

_No response_

### PR DESCRIPTION
**Pull request by suzuki-shunsuke**
Close #2175

## Test

- If tflint's fix is true, code is fixed properly https://github.com/suzuki-shunsuke/test-tfaction/pull/29
- If tflint's fix is false, code isn't fixed https://github.com/suzuki-shunsuke/test-tfaction/pull/30

### CODE REVIEW

File: js/src/get-global-config/index.ts [hunk 1]
```diff
@@ -90,6 +91,7 @@ export const main_ = (config: lib.Config, input: Input): Result => {
     enable_tfsec: config?.tfsec?.enabled ?? false,
     enable_tflint: config?.tflint?.enabled ?? true,
     enable_trivy: config?.trivy?.enabled ?? true,
+    tflint_fix: config?.tflint?.fix ?? false,
```
Comment (suzuki-shunsuke) [inline js/src/get-global-config/index.ts:94]: Add the output `tflint_fix` to get-global-config and js/get-global-config.
The default value is false.

File: test-module/action.yaml [hunk 2]
```diff
@@ -49,6 +49,7 @@ runs:
         github_token: ${{ inputs.github_token }}
         working_directory: ${{ env.TFACTION_TARGET }}
         github_comment: "true"
+        fix: ${{ steps.global-config.outputs.tflint_fix == 'true' }}
```
Comment (suzuki-shunsuke) [inline test-module/action.yaml:52]: Pass `tflint_fix` to tflint action. By default, fix is false.
